services:
  ties:
    image: ghcr.io/raffomania/ties
    depends_on:
      - db
    # For more information on the environment configuration, refer to the command line help:
    # `docker run ghcr.io/raffomania/ties --help`
    environment:
      # Interface and port to bind to.
      - LISTEN=0.0.0.0:3000
      # Where to reach the postgresql database at.
      - DATABASE_URL=postgres://ties:ties@db/ties
      # Set this to "debug" if you want more detailed logs.
      - RUST_LOG=info
      # URL for reaching the server publicly.
      # Careful: This will form the domain part of user handles, such as "rafael@ties.pub",
      # and cannot be changed once set!
      # Include the protocol when setting this.
      # Example: https://ties.pub
      - BASE_URL=
      # Optional: Create an admin user if it does not exist yet.
      # This is currently the only way to set the admin password.
      - ADMIN_USERNAME=
      - ADMIN_PASSWORD=
    ports:
      - "3000:3000"

  db:
    image: docker.io/library/postgres:18
    environment:
      - POSTGRES_DB=ties
      - POSTGRES_USER=ties
      - POSTGRES_PASSWORD=ties
    volumes:
      - db:/var/lib/postgresql
    command: |
      -c shared_buffers=16MB
      -c work_mem=1MB
      -c max_connections=10
      -c maintenance_work_mem=4MB
      -c effective_cache_size=32MB

volumes:
  db:
